### ISSUE TITLE
Broken outside of Demo

### ISSUE THREAD

**Issue by nathanchapman** [davidwittenbrink/facebook-login#9]
The component works correctly outside of a Polymer app, but once imported, only shows up in Chrome (not Safari or Firefox). In Safari and Firefox it's being rendered as 0px by 0px.

**Comment by davidwittenbrink** [comment]
Can you make sure you've imported the right definition (`dist/facebook-login.html`)? The component is written in ES15 and transpiled in order to support all browsers.

**Comment by nathanchapman** [comment]
That is totally my bad. My gulpfile wasn't replacing 'dist' in the build script. Sorry for the issue.

**Comment by emersonbottero** [comment]
Hi David, can't you make your code on a src folder and the dist in the
root? All other elements have the released version in the root.

Em sex, 29 de jan de 2016 às 00:45, Nathan Chapman <notifications@github.com>
escreveu:

**Comment by nathanchapman** [comment]
What would be the benefit of doing so? I've seen elements with both folder structures

**Comment by davidwittenbrink** [comment]
It might be a good idea to do this because all original polymer elements have the released version in the root directory. Does anybody have some reference to best practices on this?
